version: "3.9"


services:
  app:
    container_name: fastapi_app
    networks:
      - app_network
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --log-level info
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - '8000:8000'
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    container_name: database_twitter
    image: postgres:latest
    networks:
      - app_network
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5433:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data/

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - app_network
      - monitoring_network
    volumes:
      - ./app/config/prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    networks:
      - monitoring_network
    depends_on:
      - prometheus

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./app/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/api/static/:/app/api/static/
    ports:
      - '80:80'
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
  monitoring_network:
