{
 "title": "Tweeter dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=\"2xx\"}[30s])",
     "legendFormat": "{{ handler }}, {{status}}"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_requests_total[1m])",
     "legendFormat": "{{ handler }}, {{ method }}, {{ status }}"
    }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "{{ handler }}, {{ method }}"
    }
   ]
  },
  {
   "title": "Top 5 Endpoints by RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "topk(5, sum(rate(http_requests_total[1m])) by (handler))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status!=\"200\"}[1m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"fastapi\"}",
     "legendFormat": "process_cpu"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "virtual_memory" },
    { "expr": "process_resident_memory_bytes", "legendFormat": "resident_memory" }
   ]
  }
 ]
}