"""Add unique into Follower

Revision ID: 88c74a17dc0b
Revises: 9fc85e67aee6
Create Date: 2024-12-30 12:44:33.629974

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88c74a17dc0b"
down_revision: Union[str, None] = "9fc85e67aee6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_follower_followee", "followers", ["follower_id", "followee_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_follower_followee", "followers", type_="unique")
    # ### end Alembic commands ###
