"""Add user_id into Media

Revision ID: 8b547699bb06
Revises: f7af7ff0344f
Create Date: 2024-12-20 17:01:01.864286

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b547699bb06"
down_revision: Union[str, None] = "f7af7ff0344f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("media", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "media", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "media", type_="foreignkey")  # type: ignore
    op.drop_column("media", "user_id")
    # ### end Alembic commands ###
